[features]
seeds = false
skip-lint = false
[programs.localnet]
basic_counter = "GGfsrCPHdtCM1JT9YDrn463SiR6orGvyGtk6P63goCpr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/resiquents/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
