[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "5ctVKdDrrPhvrpEH2zat86QHeEk2r1ayUJFSu4Gui9k9"
data_license = "6PZWN3Vesc9G7PmgDxdZVby2UjJ4QABzf65yeEDKBrTA"
escrow = "6QC5nNLrdHDkQkoyrDLBs4hTeav1atKmWCKf447F8XSG"
program_marketplace = "2zZpWQ35TqpTwKe9fYqp5hLMkEKXeX28Peb4vsbnUZNS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/resiquents/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
